before_script:
        - pacman --noconfirm -Syu cmake boost boost-libs gcc make

build:
        script:
                - mkdir build
                - cd build
                - cmake ..
                - make
