language: c++
sudo: required
compiler:
- gcc

before_install:
- sudo apt-get install software-properties-common
- sudo add-apt-repository ppa:george-edison55/cmake-3.x
- sudo apt-get update
- sudo apt-get upgrade
- sudo apt-get install libboost-all-dev

script:
- mkdir build && cd build && cmake .. && make
