language: c++
sudo: required
compiler:
- gcc

before_install:
- sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
- sudo apt-get -qq update
- apt-get install --only-upgrade cmake
- sudo apt-get -y install libboost-all-dev

script:
- mkdir build && cd build && cmake .. && make
